name: preview

on: push

  # pushschedule:
  #   - cron: "0 2 * * 6"  # 02:00 of every Saturday

jobs:
  packaging:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version:  3.8
    - name: Install setuptools
      run: |
        python -m pip install --user --upgrade setuptools wheel
    - name: Build distribution
      run: |
        git tag 0.4dev$(date +'%y%U')
        # build tar.gz and wheel
        python setup.py sdist bdist_wheel

    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_TEST }}
        repository_url: https://test.pypi.org/legacy/

